const events = require("events");


class ProtocolPacketHandler extends events.EventEmitter {

    constructor(){
        super();
    }
    
    recv(session_id, data){
        throw Error("Must override this.");
    }

    async send_error(session_id, type, error_uri, request_id, misc){
        this.emit(
            "data", 
            session_id,
            wamp_error(type, error_uri, request_id, misc)
        );
    }

    async send(session_id, data){
        // General send function, data must be valid WAMP protocol packet,
        // which can be generated by a call to a function of
        // `messages.<DATA-TYPE>({})` builders.
        this.emit("data", session_id, data);
    }

    async send_abort(session_id, reason){
        this.send(session_id, messages.abort({
            reason: reason?reason:"wamp.close.close_realm",
            details: {},
        }));
    }
}

export default ProtocolPacketHandler;
